language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.gradle

before_install:
  - pyenv install 3.6.0
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)