language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.gradle"
before_install:
- pyenv install 3.6.0
- pip install --user codecov
after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "jamius19"
    token:
      secure: ZeZ5LH3aNHblRWc2l9bbtKvRmm+o7UOaQeD+c0i/gbwrJqImP4GTZgKeNlDaRBWukh2zLDN3RRNW3srHRWtMNc4YyRHI4xc3xPZBGehK2STR5320Ewqwftb4XOmYvW/0BoNwzUivh5S5R7RjvJm1m2FciVZK3v0cNSl7wkhTMH1cHk3f9ttBTZIkcIzqtkdWC4iQk0IIrsRMODdOitTJI+3ew9wl0y1h+70ifTR07Iim/MvCFRrSZ5lRZsVz7K8oRrCuWpjKCqh9K178g38N5H4U9+Rb/Cf2swJMtR7MhycjxNkZ+xa5qbkskdYTPCbF18EHY9UIud4vnW9PlGzPxaiVtgX2zdcyN0w7yXhdAq4HC8reXN/xAA2+Sq5IGFSoxwCA7coni4KeJC/STXlnokr+5Ys0krPgztexw7E9zTotzqmNkViUbXMqrEXw6gbx7q2VxYGvxRuKi53KALhqsH95H9Mn8JzNNIXokl2/HKR1p4m3L7o3CbUrxRui6gcFrfm0XOgjOEDqpnjJiUe3VvVhpvqDAhOeId7/hAj9ksdBEMmxmTqHWrTAbbRZ4sTk0PwgP+8Lx0HUOwM2QkBV0srGw2n74/WCc0/e58vzu9/a6TeBhxcqi2YplX6pelaPTxgSYkDPWJvgB2WIdjJtBwRmxK8pL1fDxkYeCA9Y1uU=
script:
  - ./gradlew sonarqube
