language: java
dist: trusty

script:
  - ./gradlew sonarqube

jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.gradle"
before_install:
- pyenv install 3.6.0
- pip install --user codecov
after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "jamius19"
    token:
      secure: dTkKfTYM+815SD7A9UjQ45/mZja1LoU7mMnvk7RVenuk6MOG2ozk4FEJla7JRorOzfE5CxDrYaly3J5PhhVur15V5cFcZMBA3aSRVNsSLh8iV3gRXTTKKZqqYZke5rn9/FiRSFvl+1ETALbArA52L4ri4p7ylq8ZZwZ+lFSBeyBlJkFiYizQrOiceDVq1FTGLFfJ0uuCUpaIK+fo2Abi6WNjfobQnmiXu2+gRcE17LqvBbhV1QbVu4Q64LLuZXy3CCWpgL0Tts8cn71Flpu7xa+V85TzNl9P90YNlHM+CTW5M+ILGsvqguvbDz1fTjZoOEU5PEpTPARVFiOLBv4G/H9AJgv5QpiHx1vmVafCH2Tzvx1zrW1kuzg1nTnfr5qU16gFyL6AB3MZDc/BsMHRvMMC+roPzfPo17Hxt7hvde2fe5k5fsY5GB9bOzifFbXOWrzAq8P48w5AafDkR3UqrkrM3DxagOcoSQZtELY3aznfKyAjDtbS7XdFLdPGZtQBOgHRYGoj8eHpU0O5YHhY4pfLXCseFnuwMzjO+22Xe13w0DDYcgXhKAWsB3oJQG1ZGudicrF4pA4I3w3kftMd6BghcgmAJO2vpJCkCWPW/L2CihQCa6PwQxlO+KPsz5tVZGWYtAX1y6x3xELaJuzRUfTJe77ugAaSeoWD3lZDOAE=
